---
title: "To the Behemoth"
description: |
  On leaving RStudio to join Google
author:
  - name: Sean Lopp
    url: {}
date: 09-08-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

In November 2015 I scored my dream job at RStudio, the company behind the RStudio IDE, shiny, and the soon-to-be-named tidyverse of R packages. Looking back, that offer was definitively my lucky break. I joined as the 3rd member of their sales team, the 22nd person in the company as a whole. I knew nothing about startups, I definitely had no business being in sales, but I was estatic when I shared with my grad school buddies that my new email would be sean@rstudio.com. 

Fast forward just shy of 6 years. RStudio has grown to 200 employees, our sales engineering team is approaching 20, and I am sad but excited to be moving on. This post is really written for 2028 Sean, to remember what I thought and felt at this moment. To remember the people who have been so important, and to document my speculations on the market and the world so that in 6 years I can laugh at all the unknown unknowns. 

## The somewhat short story of my time at RStudio

It is hard to summarize six years, especially when those 6 start-up years map to at least 12 years of regular company work. My attempt:

1. From 2015-2016 I worked as a customer success rep. I learned what commission was, what a non-recoverable draw entailed, and all about pharmas (our largest vertical), salesforce, and marketo. It was hard to believe that RStudio would trust a 22 year old to jump into calls with some of the largest companies in the world, its even harder to believe it worked. I still remember when my boss, the wise and sales hardened Jim Clemens, took me to a fancy bar my first day onsite in Boston. I don't think he or the bartender believed I was 22 and had an expense account! Other critical folks in this time included Pete Knast (who introduced me to sales and _real_ expense account travel) and Phil, who would become one of my closest partners in crime and the future director of life sciences.

I remember a few things about starting at RStudio that really tell how green I was. At that time I was living in a horrible housing complex where I had my own room but shared a shower and kitchen with 8 strangers. I paid 400 a month but didn't have internet. I took my RStudio interviews from the floor of a college laundromat lobby. My first day was  a Monday in RStudio's Boston office. I had booked a red-eye flight that departed Denver at 12am to avoid having to pay for an extra night's hotel fair. Unfortunately Saturday I realized that I had messed up the booking and my flight left denver Monday at midnight. I paid a $600 last minute change fee that I never expensed out of embarrassment, but set me back a months rent. When I first met RStudio's president, Tareef, I called him Kareef. He politely corrected me and then asked me how Colorado was. I said fine, and then he asked if I had ever been to Boulder. I jokingly said "the place where they believe in all that gluten nonsense?". I later learned Tareef was an ardent gluten-free adherent. It wouldn't be the last time I put my foot in my mouth, but I am pretty sure after the first 5 minutes Jim thought he had made a horrible mistake.

2. In Oct 2016 I jumped from RStudio's sales org to become the second solutions engineer. At the time this move was pretty straightforward. Nathan Stephens, the head of SE, was a generous man (who would turn out to be a dear friend and mentor). I had the technical skills to support our growing sales team, and I liked doing demos more than salesforce. Our team grew quickly over the next year, key hires included Jonathan R (the finance guru who would first break my naivety bubble and tell me about the business world outside RStudio) and Edgar Ruiz (another solutions engineer with unquenchable cheer and serious Latin coolness). 

A brief short story to reassure you that I still hadn't mastered this professional life. One week in 2016 I was asked to fly to San Jose to be the sales representative in a series of customer visits that the Hadley Wickham had agreed to attend. I would later learn that Hadley was a literal rock star, with weirdo R users asking for his autograph. My single job during this tour was to drive Hadley around. We had a full day, with a plan to meet at the airport, then drive to Intel, Genetech, and into San Fran to visit Uber. (Uber had such a weird culture, and later would be the only customer I would legitimately complain was rude and arrogant.) I showed up at the San Jose airport at 7am and texted Hadley. We were going to meet at 7:30 and arrive at Intel in time for an 8am meeting. By 7:40 we were both confused, he was texting me where he was, but I couldn't find him. Turns out that, "the airport", was SFO, not SJO. I had failed at my one job, and Hadley had to scramble to pay a Lyft 100 dollars to drive him from SFO to Intel where he calmly gave his hour long presentation in 20 minutes.

3. 2017-2018 is what I'd consider my golden years. We hired Cole Arendt - the single smartest person I've ever worked with, despite his tendency to hack faster than he could ever document. I traveled all over, including Austin, Boston, Seattle, New York, San Fran, Chicago, and Houston (where I got an exclusive tour of NASA mission control before giving one of the worst demos of my life because, while they could send a man to the moon, NASA couldn't provide reliable public internet.). Everywhere I went we got to eat amazing food, and I filled any spare time walking the streets or visiting art museums. Overtime I would also travel to Belgium (my first trip abroad) and London. I rediscovered biking (thanks to the prodding of Aron Atkins to buy a Salsa Warbird). I gave my single best presentation at the 2018 RStudio Conf in Orlando showing in real time how to scale a shiny app to 10,000 users. (The Orlando conf was incredible. We started with a RStudio exclusive evening at Harry Potter World and then JJ paid for the RStudio employees to spend the next day at the park, fast passes included! This also happened to be 7 days after my wedding.... quite the "honeymoon"?).

4. Towards the end of 2018 I started to dabble my toes in product management. I joined the sprint reviews for RStudio Connect and I started working closer with Jeff Allen (an enormously kind and talented engineering manager) and Robby Shaver (a brilliant but laid back designer who taught me that less is more in words, buttons, and just about everything but white space). (Side, side note: for some reason I consistently lied to Jeff about my age, claiming I was a few years older than I really am. This lie started because I was embarrassed to take on responsibilities while being so young, but because Jeff is so thoughtful it ultimately became worse and worse - one night he politely realized I was lying when my time in college, high school, and at RStudio didn't add up. Sorry Jeff!). I became more and more involved in our product planning, and eventually I was given the reigns to create a new product from scratch in RStudio Package Manager. The genesis of this product was partly a need to support customers in offline environments, but mostly my ambition to lead a product team. We started with a gaggle of spreadsheets and customer interviews, and thanks to Jon Yoder (a humble, quiet, and brilliant engineer) we built something special. Package Manager would fully launch in 2019, and I would lead the team through 2020. The product eventually became both a core part of RStudio's offering, accounting for millions in revenue, and it became a [public service](https://packagemanager.rstudio.com). I am most proud of how Package Manager provides pre-compiled packages for Linux. This work took a team and some clever planning, but in it I feel I've left a lasting fingerprint on the R community. Before, installing R and packages on Linux could easily take hours. Now, both R and packages come pre-compiled from RStudio. The way I know I'm successful is that occasionally the service will fail and folks will have to go back to the old method, and it is so painful as to be unfathomable! Of course none of this success was pre-destined, I learned that building a product requires countless trade-offs and a near constant diligence in engineering groomings and reviews. (Even great engineers have a tendency to never ship if left to their own choices.) During this period I also got to work on marketing content with Greg Swinehart, who is perhaps the best human being I've ever met.

5. 2019 and 2020 marked the beginning of the end, though I didn't know it at the time. In mid-2019 I formally became a full time product manager --  RStudio's first. I was woefully unprepared, and in hindsight, this position wasn't really a fair one. I was tasked with balancing our executive team's ever-changing vision, our legitimate but diverse customer requests, and our dev team's daily execution. I was soon crushed. Luckily at this time I was able to rely on the wisdom of Kris Overholt and Daniel Rodriguez,  two ex-PMs who briefly worked at RStudio and instilled in me both an earnest skepticism of the business and a keen nose for bullshit. At this time Jeff left to pursue a new team at RStudio, and so I found myself managing both RStudio Package Manager and RStudio Connect. A wiser person would have built a product managemnt team, I attempted to forge ahead on my own. I also refused to give up my work with customers which I rightly thought would ground my product work, but which I incorrectly assumed would magically take less time. A perfect recipe for burnout. This was also the period when I began to realize an unhealthy relationship with Tareef, RStudio's president. I hesitate to write much about Tareef, I won't need a blogpost to remember him. He was both a paternal figure genuinely invested in my career, an interesting corporate philosopher, and my strategic arch-enemy. I wanted to build a process that took data from our customers, aligned around a strategic vision, and then executed against a prioritized roadmap. In many ways Tareef wanted the same thing, but lived at a different level of visibility. He struggled to share his vision, and I lacked the leadership tools to clarify it, and so I often felt undermined when he would critique the team's execution or focus while simultaneously introducing new initiatives. The only way I lasted until the end of 2020 was because I was joined in product by Kelly. Kelly is one of the most strategic and empathetic people I've ever met, and in Jan 2020 she joined me in working on Connect. Mentoring Kelly was hard for me, not because of Kelly - whose work was always brilliant and 3 steps ahead of my own, but because the challenges she felt and reported back to me caused me 10x the frustration as when I felt them myself. I realized during this time just how hard it can be to be a manager or mentor, I was much better suited to dealing with shit than telling someone I cared about that I couldn't remove their obstacles. By Oct 2020 I was constantly angry, burnt out, and quick to boil into frustration with others. My wife said I had to quit. I had promised Tareef if it came to that I would give him a few months notice, so in October I told him I needed to leave. A few other things are worth noting about the fall of 2020. For one, my old solutions engineering team was imploding. Skeptical Kris had left, leaving a wake and a big hole (because he was also the most gifted solutions engineer I've worked with). Cole and James (who was and is my constant motivation in RStudio's cycling strava) were both on paternity leave. Edgar, the other old goat from 2017, had abruptly quit at the beginning of the year. This proved a tough load, and it ultimately contributed to Nathan stepping away from the director role. In short, it was a total and complete dumpster fire, and I found myself in the midst of my struggles with product attempting to hold together the fragile remains of the SE team.

6. Enter 2021. My big question after telling Tareef I was done was "what's next?". This question turned out to be quite the doozy. I temporarily opted to return to solutions engineering, and like most things in my life this short term choice turned out to be insanely lucky. After 9 months of reflection it is easier for me to understand that sales engineering is where I should continue next, but that realization came after quite a few false starts. I applied and almost accepted a consulting job that would have returned me to my college work of energy analytics and 10 hour days of coding. I applied and was accepted to law school. I even read all about other product roles, teams, and domains. In June I took two weeks off to attend a wedding in Alaska and travel the state. During this time, and there was a LOT of time driving, I realized that I really enjoyed my time with our sales team. I have been lucky to work alongside really excellent account executives in Jason Miles, Kevin Hayden, Sabrina, Lauren, Nichole, Dylan, and countless others. Unlike product management, where the objectives are ambiguous and the time frames are measured in years, sales had a clear directive. Yes, there is still an art to asking questions and aligning around value, but our team was always on the same page. The rewards were satisfying and aligned with compensation. The customers were diverse and interesting. Finally, in my year of renewed SE focus, I rediscovered that I was really good at sales engineering. I had unknowingly felt like an imposter as a product manager, always quite certain that I had no business representing the needs of any users, desperately trying to read the market tea leaves while directing millions of dollars in dev investment. Ultimately I realized I was in the right role as an SE,  which led to a natural question, how do I get better and go further? This question has taken awhile to answer, but it is what leads me to Google. I need to be exposed to something outside of RStudio, to learn how other organizations and sales teams operate, to sell different products, in different frameworks, to different customers. I realized, with both happiness and sorrow, that I need to leave RStudio.

You may be wondering whats to come of the SE team that was struggling in 2020 and that I luckily rejoined in earnest in 2021. To answer that question I have to introduce a few more characters. Alex Gold joined RStudio in 2019 as an SE after giving an excellent interview with a few too many memes. He is proving to be both a talented "get shit done" organizer and a thoughtful manager who will carry the team. Andrie joined RStudio in 2017 and has had a knack for doing the dirtiest work, and I expect he will continue that trend. David joined RStudio in 2020 and shares my knack for sarcasm, dread, and picking up new tools quickly and holistically. Others deserve mention as marvelous people who I worked with less but still hold dear: Gagan, Ian, Ralf, Mark, and Lou (the most diligently organized product marketer).

It is also worth mentioning that during 2021 I had the privilege of working with an executive coach. I spent 6 months working every other week with an older gentlemen named Harry. Harry's superpower is very quickly seeing to the heart of things. The main thing Harry helped me realize was that I was responsible when people misunderstood me, or I misunderstood them. He taught me to convince others by teaching them not telling them (slow down and ask questions you sometimes know the answer to). He taught me to ask questions I didn't know the answer to, again and again, to try and help others show me their work. Most of all, he taught me that Pixar's Inside Out is actually pretty accurate, and that feelings serve their best purpose when they work together. Or, the Aristotelian take, prudence is the heart of all virtues.

In closing this short story, I still struggle to imagine that this chapter is coming to a close. I can still put myself in the middle of some of my best and fondest memories:  

- drinking a beer with Phil at O'hare after a long drive from Abbott
- sitting in between Alex, Greg, and Joe C at a bar talking about music  
- yelling at a planetarium screen after one too many drinks with Tyler while Kelly watched mortified, and then later that evening finding my way into an amazing halal place with Alex  
- sitting with Nathan at a poolside lounge talking for hours about the importance of good mattress selection  
- sipping wine with Mark E in Chicago, pretending I could tell the difference between four reds  
- eating an absurdly expensive hamburger with Jonathan off of Wall Street  
- driving through a blizzard to spend 3 nights onboarding Jason at Jim's lakeside mansion/cabin, and our "team building" 2 mile hike post-holing through 2 ft deep snow up the side of a mountain. (Jim is in remarkable shape)  
- walking around Mountain View at 11pm eating ice cream with Phil and Tareef after meeting with a bunch of pharmas, listening to Tareef tell us his life story  
- attending JJ's birthday party, complete with amazing finger food and dancers spray painted to look like robots  
- riding the London tube for the first time, and then 8 days later for the last time, feeling rather comfortable as I recognized the route names  
- navigating the middle of no-where Cambridge with Tareef trying to find AztraZeneca's headquarters, and Tareef's kindness when he stopped at a small cafe even though he doesn't drink coffee  
- eating benets in New Orleans late at night with our whole SE team  
- arguing about Looper in a hipster food court  


## A shorter TL:DR of a few things I learned at RStudio

1. Inbound sales can be amazing. RStudio built a business with almost zero marketing, close to 3 million a rep, and an average deal size of 30K ACV. While the deals got larger and the account load smaller, I learned that an open source community, great products, and low pricing can sustain an incredibly leveraged business.

2. On-premise products have pros and cons. Integrating with disparate architectures is hard, and on-prem system admins can be hit or miss. BUT, for free, we were able to position ourselves as multi-cloud or hybrid, and our marginal costs were truly $0!

3. Stock options. They are a lottery, but worth exercising early if they are cheap.

4. As companies grow its easy to think the sky is falling with every change. Hold back chicken little.

5. The sales team really does eat and drink the best. Hang out with them when you travel.

6. My most lasting product efforts required the alignment and patience of a large team. My most fun efforts required under-the-radar teamwork with 1 or 2 individuals who knew how to get shit done.

7. Interviewing is really hard. Be patient and hold out for people who generate an absolute yes. Any qualities you notice in an interview (sloppy with details, talkative, a little arrogant) will become more and more pronounced when you work with them. People who know their shit can talk about it at different levels, and will lead you deeper. (If YOU have to keep asking questions to probe for someone's concrete knowledge, its likely they don't have much!) Further, if someone explains something and you don't understand it, its not because you are a dummy -- they've failed the task. 

8. Marketing is important, but easy to shit on because no one can really say if its working. When a deal is closed won its "because of sales", when a deal is closed lost, its "because of product".

9. Small teams of independent professionals are amazing, but they are really hard to scale. Larger teams need more process to stay afloat. 

10. As a leader, "showing up" to every meeting is important. No team meeting or 1:1 can be handled casually, so skip it if you're not in the right head space. Your job is almost always to present ideas with optimism, absorb (not amplify) the natural concerns around ambiguity, and remain professional. All that said, it can be really helpful to have a few peers to whom you can vent and "let down your guard", but gossip isn't a shortcut to being considered genuine.

11. Keyboard shortcuts in gmail are clutch, as is Alfred, zsh, the reveal bullshit plugin, and hard restarting chrome every morning.

12. After countless hours in many airports I can confirm that O'hare is the worst, JFK is the most inconvenient, and as Phil would proudly tell you, Indy is the best. A few other airport comments - if you are going to downtown Chicago, take the blue line not a rental car. (Except if it is Lalapalooza week, then definitely do NOT take the train.) In Denver, the fastest way to get from driving to your gate is to park in the southern end of the west lot, walk through the Westin, up the escalators, through South security, and onto the train. Patagonia black hole 40L duffles are _the optimal 2-3 day trip bag_ as they can fit under the seat in a pinch and fit on your back. People who roll their luggage are slower, can't run down escalators, and look like idiots walking downtown. Never gate check a bag. Only fly direct. TSA pre-check is the single best investment you can make.

## Thoughts about Data, Analytics, and Statistics

Anyone who knows me well (or even a little) knows I hate the Gartner Magic Quadrant. Here are my anecdotal hot takes. 

1. JavaScript might eat the world, but SQL already has and will again. I am very bullish on groups like Observable. Data products that only need a browser are pretty sweet. Those products, however, aren't great at data prep -- enter SQL. I was slow to realize that every meaningful bit of code I've dogfooded at RStudio has just been SQL in disguise. I'm super bullish on products that make SQL better, R included? I can't wait to follow Dremio, Voltron Data, and dbt. Those are 3 rocket ships.

2. I love RStudio Connect. Domino and Dataiku I really don't understand. If you want infrastructure and project  orchestration then Sagemaker, GCP Notebooks, Azure ML, etc are sufficient. Connect is unique in it's ability to host an R or Python app outside of a development context. While Connect hasn't quite figured out if its a BI tool for data scientists or an execution service for R and Python (like Heroku), I sort of love that it lives in its own grey area. I am certain Kelly will ensure it keeps delighting users despite its lack of a coherent category.

3. Some modelling activities are actually data engineering in disguise. NLP, image recognition, deep learning, most of them are just to get non-tabular data into a SQL-able form. Corollary 1: Most ML hyped production use cases are either just counting or could be served by just counting. Corollary 2: Databricks is valuable for teams that need to do SQL on larger-than-SQL data, but SQL warehouses are getting bigger and bigger so I really don't understand their multi-billon dollar valuation. The rest of their lineup, MLOps and what not, probably isn't very real.

4. Statistics is all about helping identify if an insight discovered in an analysis is legitimate or could be the result of random chance. In many cases, executive leadership won't care. Boxplots are better than bar charts, but many executives won't get them. 

5. The FDA is the most insane regulatory body I have ever encountered, and paints a grim picture of what "digital transformation" looks like in government. Feel what you will about big pharma, the idea that they have to submit data on clinical trials as plain text files according to a 1999 spec is crazy. SAS rules this land because the FDA is unwilling to change, and their claim to be language agnostic is tantamount to fraud.

6. Most data science companies, especially start-ups, are consultants in disguise. This has pros and cons. Consulting keeps you close to your users and helps build better products. It can also lead to VCs pouring stupid amounts of money into vaporware (ahem -  plotly, streamlit, and also IBM Watson?). 

7. h2o.ai is legitimate and building interesting AI techniques. Domo and DataRobot are not.

8. Kubernetes lives up to the hype and its worth learning. Overtime the patterns make sense and the helm templates become readable. Chef recipes, on the other hand, will never make sense.


## Looking towards Google 

I'm not sure what to expect next, except that Google will be different. I hope this pandemic ends and I get to enjoy their famed lunches. I hope that I can get up to speed on BI, that SQL really does continue to eat the world, and that JavaScript becomes less confusing. I am excited to learn about the GCP landscape, especially data engineering which is a critical part of my SQL + JavaScript dominates the world prediction. Most of all, I hope I am fortunate enough to find myself with a team that is half as humble, hungry, and kind as my current colleagues and friends.


